AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 180

Style/IfUnlessModifier:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: ["x", "y", "to", "r", "g", "b", "a", "up"]

Naming/VariableNumber:
  EnforcedStyle: snake_case

Metrics/MethodLength:
  Max: 15

Style/AccessorGrouping:
  Enabled: false

Metrics/ModuleLength:
  Max: 180

Metrics/ClassLength:
  Max: 180

Style/RedundantParentheses:
  Enable: false

Style/ParenthesesAroundCondition:
  Enabled: false
