# frozen_string_literal: true
require "gosu"

require_relative "fantasy/version"
require_relative "fantasy/draggable"
require_relative "fantasy/color"
require_relative "fantasy/actor"
require_relative "fantasy/coordinates"
require_relative "fantasy/utils"
require_relative "fantasy/global"
require_relative "fantasy/clock"
require_relative "fantasy/loop"
require_relative "fantasy/hud_text"
require_relative "fantasy/hud_image"
require_relative "fantasy/sound"
require_relative "fantasy/camera"
require_relative "fantasy/base"
