# frozen_string_literal: true

require "gosu"

require_relative "fantasy/version"

require_relative "fantasy/coordinates"
require_relative "fantasy/cursor"
require_relative "fantasy/mouse"
require_relative "fantasy/internals/collision_resolver"
require_relative "fantasy/includes/log"
require_relative "fantasy/includes/move_by_cursors"
require_relative "fantasy/includes/move_by_direction"
require_relative "fantasy/includes/mover"
require_relative "fantasy/includes/gravitier"
require_relative "fantasy/includes/jumper"
require_relative "fantasy/includes/user_inputs"
require_relative "fantasy/includes/indexable"
require_relative "fantasy/tweeni"
require_relative "fantasy/draggable"
require_relative "fantasy/color"
require_relative "fantasy/shape"
require_relative "fantasy/actor"
require_relative "fantasy/collider"
require_relative "fantasy/utils"
require_relative "fantasy/global"
require_relative "fantasy/clock"
require_relative "fantasy/loop"
require_relative "fantasy/hud_text"
require_relative "fantasy/hud_image"
require_relative "fantasy/animation"
require_relative "fantasy/background"
require_relative "fantasy/sound"
require_relative "fantasy/music"
require_relative "fantasy/camera"
require_relative "fantasy/image"
require_relative "fantasy/tilemap"
require_relative "fantasy/base"
require_relative "fantasy/disk"
