# frozen_string_literal: true

# Represents on static image that will be rendered on every frame.
# Replicable (by default).
# The position is relative to `Camera.main`.
# ```
# on_game do
#   background = Background.new(graphic: "beach")
#   # background.repeat = false # if you don't want the image to replicate
#   background.scale = 6
# end
# ```
class Background
  include Log
  include Indexable

  # In which layer the image of the Background is rendered.
  # Smaller numbers are rendered behind higher numbers.
  #
  # Default `-100`.
  #
  # @example Set layer
  #   background = Background.new("image")
  #   background.layer = -50
  attr_accessor :layer

  # Coordinates object where x and y represent the position of the Background in the World
  # (no necessarily in the Screen).
  #
  # Default `Coordinates.zero`.
  #
  # @example Setting position
  #   background = Background.new("image")
  #   background.position = Coordinates.new(10, 20)
  #   background.position.x # => 10
  #
  # @example Modify position
  #   background.position.x +=  1
  #   background.position.x # => 11
  attr_accessor :position

  # [Boolean] When `true` the image will replicate itself to cover all the screen.
  # [symbol] When `:both` is the same as `true`
  #          When `:vertical` only repeats vertically
  #          When `:horizontal` only repeats horizontally
  #
  # Default `true`.
  #
  # @example Setting repeat to `false`
  #   background = Background.new("image")
  #   background.repeat = false
  attr_accessor :repeat

  # The value to scale the image of the Background when drawn.
  # If the value is `2` the image will rendered at double of size.
  # If the value is `0.5` the image will rendered at half of size.
  #
  # @note this value affects the attributes `width` and `height`
  #
  # Default `1`.
  #
  # @example Set scale
  #   background = Background.new("image")
  #   background.scale = 6
  attr_accessor :scale

  # When `false` the Background won't be rendered in the next frame.
  #
  # Default `true`.
  #
  # @example Set visible
  #   background = Background.new("image")
  #   background.visible = false
  attr_accessor :visible

  # Generates an Background with all the below default values:
  # - **position**: `Coordinates.zero`.
  # - **scale**: `1`.
  # - **draggable_on_debug**: `true`.
  # - **layer**: `-100`.
  # - **image**: The Image generated by `graphic`
  # - **name**: Same as `graphic`
  # - **visible**: `true`
  # - **repeat**: `false`
  #
  # @param graphic [string] the name of the image file from `./images/*`
  # @return [Background] the Background
  # @example Instantiate a new Background
  #   background = Background.new("background")
  def initialize(graphic:)
    @image = Image.load(graphic)
    @position = Coordinates.zero
    @scale = 1
    @visible = true
    @draggable_on_debug = true
    @dragging = false
    @layer = -100
    @repeat = true

    Global.backgrounds&.push(self)
  end

  # @return [Fixnum] the Background width in pixels
  def width
    @image.width * @scale
  end

  # @return [Fixnum] the Background height in pixels
  def height
    @image.height * @scale
  end

  # rubocop:disable Style/GuardClause

  # @!visibility private
  def draw
    if @visible
      if @repeat
        draw_repeat
      else
        draw_normal
      end
    end
  end
  # rubocop:enable Style/GuardClause

  # Destroy this Background and it will not longer be rendered
  #
  # @example Destroy a Background
  #   background = Background.new("background")
  #   background.destroy
  def destroy
    log("#destroy")
    Global.backgrounds.delete(self)
  end

  def layer_in_world
    layer
  end

  private

  def position_in_camera
    @position - Camera.main.position
  end

  # Camera relative Tiles
  def draw_repeat
    first_tile_position_x = position_in_camera.x
    first_tile_position_y = position_in_camera.y

    tiles_needed_horizontal = 1
    tiles_needed_vertical = 1

    if repeat_horizontally?
      tiles_needed_horizontal = (Global.screen_width / width.to_f).ceil + 1
      first_tile_position_x = position_in_camera.x - ((position_in_camera.x / width.to_f).ceil * width)
    end

    if repeat_vertically?
      tiles_needed_vertical = (Global.screen_height / height.to_f).ceil + 1
      first_tile_position_y = position_in_camera.y - ((position_in_camera.y / height.to_f).ceil * height)
    end

    tiles_needed_horizontal.times do |index_horizontal|
      tiles_needed_vertical.times do |index_vertical|
        drawing_position =
          Coordinates.new(
            first_tile_position_x + (width * index_horizontal),
            first_tile_position_y + (height * index_vertical)
          )
        @image.draw(position: drawing_position, scale: @scale)
      end
    end
  end

  def draw_normal
    @image.draw(position: position_in_camera, scale: @scale)
  end

  def repeat_horizontally?
    [:both, :horizontal, true].include?(@repeat)
  end

  def repeat_vertically?
    [:both, :vertical, true].include?(@repeat)
  end
end
